version: '2'
services:
    prova1-app:
        image: prova1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://prova1-postgresql:5432/prova1
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=prova1-elasticsearch:9300
        ports:
            - 8080:8080
    prova1-postgresql:
        extends:
            file: postgresql.yml
            service: prova1-postgresql
    prova1-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: prova1-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
